export const MSG_ADD_TO_CART_SUCCESS = "ADD TO CART SUCCESS";
export const MSG_UPDATE_CART_SUCCESS = "UPDATE CART SUCCESS";
export const MSG_DELETE_CART_SUCCESS = "DELETE CART SUCCESS";
export const MSG_CART_EMPTY = "CART IS EMPTY";
export const MSG_WELCOME = "WELCOME";